on:
  push:
    paths:
      - "C:\Users\breno\OneDrive\Área de Trabalho\Hacker_Rank"

- name: Add files
  run:
    git config -- local user.name "elpitta"
    git config -- local user.email "brenobpitta@gmail.com"
    git add sql_files
    
- name: Commit and push
  run: |
    git commit -m "Adicionando arquivos SQL"
    git push
